-- Buat tabel wilayah
CREATE TABLE IF NOT EXISTS tb_wilayah (
    id INT AUTO_INCREMENT PRIMARY KEY,
    propinsi VARCHAR(100) NOT NULL,
    kota VARCHAR(100) NOT NULL,
    kecamatan VARCHAR(100) NOT NULL,
    kelurahan VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Masukkan data contoh untuk DKI Jakarta
INSERT INTO tb_wilayah (propinsi, kota, kecamatan, kelurahan) VALUES
('DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Gambir'),
('DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Cideng'),
('DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Petojo Utara'),
('DKI Jakarta', 'Jakarta Pusat', 'Gambir', 'Petojo Selatan'),
('DKI Jakarta', 'Jakarta Pusat', 'Tanah Abang', 'Kebon Melati'),
('DKI Jakarta', 'Jakarta Pusat', 'Tanah Abang', 'Kebon Kacang'),
('DKI Jakarta', 'Jakarta Pusat', 'Tanah Abang', 'Kampung Bali'),
('DKI Jakarta', 'Jakarta Pusat', 'Tanah Abang', 'Petamburan'),
('DKI Jakarta', 'Jakarta Pusat', 'Menteng', 'Menteng'),
('DKI Jakarta', 'Jakarta Pusat', 'Menteng', 'Pegangsaan'),
('DKI Jakarta', 'Jakarta Pusat', 'Menteng', 'Cikini'),
('DKI Jakarta', 'Jakarta Pusat', 'Menteng', 'Gondangdia'),
('DKI Jakarta', 'Jakarta Pusat', 'Senen', 'Senen'),
('DKI Jakarta', 'Jakarta Pusat', 'Senen', 'Kwitang'),
('DKI Jakarta', 'Jakarta Pusat', 'Senen', 'Kenari'),
('DKI Jakarta', 'Jakarta Pusat', 'Senen', 'Paseban'),
('DKI Jakarta', 'Jakarta Pusat', 'Johar Baru', 'Johar Baru'),
('DKI Jakarta', 'Jakarta Pusat', 'Johar Baru', 'Kampung Baru'),
('DKI Jakarta', 'Jakarta Pusat', 'Johar Baru', 'Tanah Tinggi'),
('DKI Jakarta', 'Jakarta Pusat', 'Johar Baru', 'Galur'),
('DKI Jakarta', 'Jakarta Pusat', 'Kemayoran', 'Kemayoran'),
('DKI Jakarta', 'Jakarta Pusat', 'Kemayoran', 'Serdang'),
('DKI Jakarta', 'Jakarta Pusat', 'Kemayoran', 'Sumur Batu'),
('DKI Jakarta', 'Jakarta Pusat', 'Kemayoran', 'Utan Panjang'),
('DKI Jakarta', 'Jakarta Pusat', 'Sawah Besar', 'Sawah Besar'),
('DKI Jakarta', 'Jakarta Pusat', 'Sawah Besar', 'Mangga Dua Selatan'),
('DKI Jakarta', 'Jakarta Pusat', 'Sawah Besar', 'Mangga Dua Utara'),
('DKI Jakarta', 'Jakarta Pusat', 'Sawah Besar', 'Karang Anyar'),
('DKI Jakarta', 'Jakarta Pusat', 'Sawah Besar', 'Kartini'),
('DKI Jakarta', 'Jakarta Utara', 'Penjaringan', 'Penjaringan'),
('DKI Jakarta', 'Jakarta Utara', 'Penjaringan', 'Pluit'),
('DKI Jakarta', 'Jakarta Utara', 'Penjaringan', 'Pejagalan'),
('DKI Jakarta', 'Jakarta Utara', 'Penjaringan', 'Kapuk Muara'),
('DKI Jakarta', 'Jakarta Utara', 'Penjaringan', 'Muara Angke'),
('DKI Jakarta', 'Jakarta Utara', 'Pademangan', 'Pademangan Barat'),
('DKI Jakarta', 'Jakarta Utara', 'Pademangan', 'Pademangan Timur'),
('DKI Jakarta', 'Jakarta Utara', 'Tanjung Priok', 'Tanjung Priok'),
('DKI Jakarta', 'Jakarta Utara', 'Tanjung Priok', 'Kebon Bawang'),
('DKI Jakarta', 'Jakarta Utara', 'Tanjung Priok', 'Sungai Bambu'),
('DKI Jakarta', 'Jakarta Utara', 'Tanjung Priok', 'Papanggo'),
('DKI Jakarta', 'Jakarta Utara', 'Tanjung Priok', 'Warakas'),
('DKI Jakarta', 'Jakarta Utara', 'Tanjung Priok', 'Sungai Bambu'),
('DKI Jakarta', 'Jakarta Utara', 'Koja', 'Koja'),
('DKI Jakarta', 'Jakarta Utara', 'Koja', 'Rawa Badak Utara'),
('DKI Jakarta', 'Jakarta Utara', 'Koja', 'Rawa Badak Selatan'),
('DKI Jakarta', 'Jakarta Utara', 'Koja', 'Tugu Utara'),
('DKI Jakarta', 'Jakarta Utara', 'Koja', 'Tugu Selatan'),
('DKI Jakarta', 'Jakarta Utara', 'Koja', 'Lagoa'),
('DKI Jakarta', 'Jakarta Utara', 'Kelapa Gading', 'Kelapa Gading Barat'),
('DKI Jakarta', 'Jakarta Utara', 'Kelapa Gading', 'Kelapa Gading Timur'),
('DKI Jakarta', 'Jakarta Utara', 'Kelapa Gading', 'Pegangsaan Dua'),
('DKI Jakarta', 'Jakarta Utara', 'Cilincing', 'Cilincing'),
('DKI Jakarta', 'Jakarta Utara', 'Cilincing', 'Semenanjung'),
('DKI Jakarta', 'Jakarta Utara', 'Cilincing', 'Rorotan'),
('DKI Jakarta', 'Jakarta Utara', 'Cilincing', 'Marunda'),
('DKI Jakarta', 'Jakarta Utara', 'Cilincing', 'Kalibaru'),
('DKI Jakarta', 'Jakarta Utara', 'Cilincing', 'Sukapura');

-- Masukkan data contoh untuk Jawa Barat
INSERT INTO tb_wilayah (propinsi, kota, kecamatan, kelurahan) VALUES
('Jawa Barat', 'Bandung', 'Andir', 'Andir'),
('Jawa Barat', 'Bandung', 'Andir', 'Campaka'),
('Jawa Barat', 'Bandung', 'Andir', 'Garuda'),
('Jawa Barat', 'Bandung', 'Andir', 'Kebon Jeruk'),
('Jawa Barat', 'Bandung', 'Andir', 'Maleber'),
('Jawa Barat', 'Bandung', 'Andir', 'Maleer'),
('Jawa Barat', 'Bandung', 'Astana Anyar', 'Astana Anyar'),
('Jawa Barat', 'Bandung', 'Astana Anyar', 'Panjunan'),
('Jawa Barat', 'Bandung', 'Astana Anyar', 'Pungkur'),
('Jawa Barat', 'Bandung', 'Astana Anyar', 'Regol'),
('Jawa Barat', 'Bandung', 'Astana Anyar', 'Suka Asih'),
('Jawa Barat', 'Bandung', 'Astana Anyar', 'Suka Galih'),
('Jawa Barat', 'Bandung', 'Bandung Kidul', 'Batununggal'),
('Jawa Barat', 'Bandung', 'Bandung Kidul', 'Kujangsari'),
('Jawa Barat', 'Bandung', 'Bandung Kidul', 'Mengger'),
('Jawa Barat', 'Bandung', 'Bandung Kidul', 'Wates'),
('Jawa Barat', 'Bandung', 'Bandung Wetan', 'Citarum'),
('Jawa Barat', 'Bandung', 'Bandung Wetan', 'Dago'),
('Jawa Barat', 'Bandung', 'Bandung Wetan', 'Lebak Siliwangi'),
('Jawa Barat', 'Bandung', 'Bandung Wetan', 'Malabar'),
('Jawa Barat', 'Bandung', 'Bandung Wetan', 'Sekeloa'),
('Jawa Barat', 'Bandung', 'Bandung Wetan', 'Sukamaju'),
('Jawa Barat', 'Bandung', 'Bandung Wetan', 'Sukarasa'),
('Jawa Barat', 'Bandung', 'Buahbatu', 'Batununggal'),
('Jawa Barat', 'Bandung', 'Buahbatu', 'Kujangsari'),
('Jawa Barat', 'Bandung', 'Buahbatu', 'Mengger'),
('Jawa Barat', 'Bandung', 'Buahbatu', 'Wates'),
('Jawa Barat', 'Bandung', 'Cibeunying Kaler', 'Cigadung'),
('Jawa Barat', 'Bandung', 'Cibeunying Kaler', 'Cihaurgeulis'),
('Jawa Barat', 'Bandung', 'Cibeunying Kaler', 'Cipedes'),
('Jawa Barat', 'Bandung', 'Cibeunying Kaler', 'Dungus Cariang'),
('Jawa Barat', 'Bandung', 'Cibeunying Kaler', 'Neglasari'),
('Jawa Barat', 'Bandung', 'Cibeunying Kaler', 'Sukamaju'),
('Jawa Barat', 'Bandung', 'Cibeunying Kidul', 'Cicadas'),
('Jawa Barat', 'Bandung', 'Cibeunying Kidul', 'Cikutra'),
('Jawa Barat', 'Bandung', 'Cibeunying Kidul', 'Padasuka'),
('Jawa Barat', 'Bandung', 'Cibeunying Kidul', 'Pasirlayung'),
('Jawa Barat', 'Bandung', 'Cibeunying Kidul', 'Sukamaju'),
('Jawa Barat', 'Bandung', 'Cibeunying Kidul', 'Sukapada');

-- Masukkan data contoh untuk Jawa Tengah
INSERT INTO tb_wilayah (propinsi, kota, kecamatan, kelurahan) VALUES
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Bangunharjo'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Brumbungan'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Gabahan'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Karang Kidul'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Kauman'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Kemijen'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Miroto'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Pandansari'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Pekunden'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Pindrikan Kidul'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Pindrikan Lor'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Purwodinatan'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Sekayu'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Sukorejo'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Tandang'),
('Jawa Tengah', 'Semarang', 'Semarang Tengah', 'Tirto'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Bandarharjo'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Bulu Lor'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Dadapsari'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Kuningan'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Panggung Kidul'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Panggung Lor'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Plombokan'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Purwosari'),
('Jawa Tengah', 'Semarang', 'Semarang Utara', 'Tanjung Mas'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Bugangan'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Dadapsari'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Karang Tempel'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Karangturi'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Kebonagung'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Kemijen'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Mlatibaru'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Mlatiharjo'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Rejomulyo'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Rejosari'),
('Jawa Tengah', 'Semarang', 'Semarang Timur', 'Sarirejo'); 